spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/batchdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver

  main:
    web-application-type: none

  batch:
    jdbc:
      initialize-schema: never # Spring BatchのDDLは流さない（既に作成済み）

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql # Batchのschema-mariadb.sqlは外す
      encoding: UTF-8
      continue-on-error: true # 既存でも止めない
