spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/batchdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.batch.domain
  configuration:
    map-underscore-to-camel-case: true
